define: DUK_USE_ERRCREATE
feature_enables: DUK_OPT_AUGMENT_ERRORS
introduced: 1.0.0
default: true
tags:
  - ecmascript
description: >
  Call Duktape.errCreate() when augmenting an Ecmascript error object
  being created.
