define: DUK_USE_COROUTINE_SUPPORT
feature_enables: DUK_OPT_COROUTINE_SUPPORT
introduced: 2.0.0
default: true
tags:
  - execution
description: >
  Enable support Duktape coroutines, i.e. yield/resume.
