define: DUK_USE_HOBJECT_HASH_PART
feature_snippet: |
  /* For now, hash part is dropped if and only if 16-bit object fields are used. */
  #define DUK_USE_HOBJECT_HASH_PART
  #if defined(DUK_OPT_OBJSIZES16)
  #undef DUK_USE_HOBJECT_HASH_PART
  #endif
introduced: 1.1.0
default: true
tags:
  - lowmemory
  - experimental
description: >
  Use a hash table for objects that have enough properties.  This should be
  enabled unless the target is very low on memory.

  If DUK_USE_OBJSIZES16 is defined, this option must not be defined.

# FIXME: expose property limit for hash table as a DUK_USE_xxx flag?
