define: DUK_USE_EXEC_INDIRECT_BOUND_CHECK
feature_snippet: |
  #undef DUK_USE_EXEC_INDIRECT_BOUND_CHECK
  #if defined(DUK_OPT_DEBUG) || defined(DUK_OPT_ASSERTIONS)
  /* Enabled with debug/assertions just so that any issues can be caught. */
  #define DUK_USE_EXEC_INDIRECT_BOUND_CHECK
  #endif
introduced: 1.0.0
default: false
tags:
  - execution
  - debug
description: >
  For opcodes with indirect indices, check final index against stack size.
  Useful for diagnosing problems.  Normally this check is not necessary
  because the compiler is trusted, and we don't bound check direct indices
  either.
