define: DUK_USE_ES6_OBJECT_SETPROTOTYPEOF
feature_enables: DUK_OPT_ES6_OBJECT_SETPROTOTYPEOF
introduced: 1.0.0
default: true
tags:
  - ecmascript
  - ecmascript6
description: >
  Provide the non-standard (ES6) Object.setPrototypeOf method.
