define: DUK_USE_STRLEN16
feature_enables: DUK_OPT_STRLEN16
introduced: 1.1.0
default: false
tags:
  - lowmemory
  - experimental
description: >
  Use a 16-bit string length field (for low memory environments).
