define: DUK_USE_ES6_OBJECT_PROTO_PROPERTY
feature_enables: DUK_OPT_ES6_OBJECT_PROTO_PROPERTY
introduced: 1.0.0
default: true
tags:
  - ecmascript
  - ecmascript6
description: >
  Provide the non-standard (ES6) Object.prototype.__proto__ property.
