define: DUK_USE_DOUBLE_ME
feature_snippet: |
  #if defined(DUK_OPT_FORCE_BYTEORDER)
  #if (DUK_OPT_FORCE_BYTEORDER == 1)
  #undef DUK_USE_DOUBLE_ME
  #elif (DUK_OPT_FORCE_BYTEORDER == 2)
  #define DUK_USE_DOUBLE_ME
  #elif (DUK_OPT_FORCE_BYTEORDER == 3)
  #undef DUK_USE_DOUBLE_ME
  #else
  #error invalid DUK_OPT_FORCE_BYTEORDER
  #endif
  #else
  #undef DUK_USE_DOUBLE_ME
  #endif
introduced: 1.0.0
removed: 1.4.0
default: false
conflicts:
  - DUK_USE_DOUBLE_LE
  - DUK_USE_DOUBLE_BE
tags:
  - portability
description: >
  IEEE double memory representation is mixed endian on the target platform.
  In other words the logical bytes ABCDEFGH are represented in memory as
  DCBAHGFE.  This endianness is used by some ARM platforms.
