define: DUK_USE_FUNCPTR_ENC16
feature_snippet: |
  #if defined(DUK_OPT_FUNCPTR_ENC16)
  #define DUK_USE_FUNCPTR_ENC16(udata,ptr) DUK_OPT_FUNCPTR_ENC16((udata),(ptr))
  #else
  #undef DUK_USE_FUNCPTR_ENC16
  #endif
introduced: 1.1.0
requires:
  - DUK_USE_FUNCPTR16
default: false
tags:
  - lowmemory
  - experimental
description: >
  Use together with DUK_USE_FUNCPTR16 for arbitrary data pointer compression.
  DUK_USE_FUNCPTR_DEC16(udata,x) is a macro with a userdata and duk_uint16_t
  argument, and a void ptr return value.  The userdata argument is the heap
  userdata value given at heap creation.
