#
#  Each Duktape option is described as a YAML file named OPTION_NAME.yaml.
#  YAML is used because it diffs well and has clean support for multiline
#  inline strings.
#

# C #define name for the option.  Must match filename minus extension.
define: DUK_USE_OBJSIZES16

# Optional list of deprecated feature defines related to this option.
# Useful so that we can issue automatic warnings/errors for deprecated
# feature options.
related_feature_defines:
  - DUK_OPT_OBJSIZES16

# Feature define (DUK_OPT_xxx) enables config define (DUK_USE_xxx), and
# negative feature define (DUK_OPT_NO_xxx) disables config define.  If
# neither present, use default.
#feature_enables: DUK_OPT_OBJSIZES16

# Feature define disables config define, and vice versa.
#feature_disables: DUK_OPT_OBJSIZES16

# Feature detection snippet given explicitly.
#feature_snippet: |
#   #if defined(DUK_OPT_OBJSIZES16)
#   #define DUK_USE_OBJSIZES16
#   #if defined(XYZ)
#   #error DUK_OPT_OBJSIZES16 conflicts with XYZ
#   #endif
#   #endif

# Feature default value is provided by platform, compiler, or architecture.
# DUK_OPT_xxx handling can force the value if explicitly requested by
# DUK_OPT_XXX or DUK_OPT_NO_xxx, but if neither is given, don't emit a
# default.
#feature_no_default: true

# Duktape version number where this option was first introduced.
introduced: 1.1.0

# Optional Duktape version number where this option was deprecated,
# i.e. the option is supported but no longer recommended.
# FIXME: automatic #error with some -DDUK_USE_NO_DEPRECATED flag?
#deprecated: 1.2.0

# Optional Duktape version number where this option was removed,
# i.e. the option is no longer supported but we may want to issue
# a clear #error for it.
#removed: 1.3.0

# Optional indication that config option is defined but currently
# unused, so that it can be omitted from generated header.
#unused: true

# Optional list of options that must also be defined to use this option.
#requires:
#  - DUK_USE_FOO
#  - DUK_USE_BAR

# Optional list of options that this option conflicts with.
#conflicts:
#  - DUK_USE_BAZ

# Optional list of options that are related from a user and documentation
# perspective.
#related:
#  - DUK_USE_QUUX

# Default value for option:
# - false: undefined (#undef DUK_USE_EXAMPLE)
# - true: defined with no value (#define DUK_USE_EXAMPLE)
# - string: defined with string value (#define DUK_USE_EXAMPLE "foo")
# - number: defined with number value (#define DUK_USE_EXAMPLE 123)
# FIXME: verbatim? #define DUK_USE_EXAMPLE do { } while (0)
default: false

# Tags related to option (required).  If present, first tag is used as a
# primary tag for grouping.  Use 'misc' if nothing else is appropriate.
tags:
  - lowmemory
  - experimental

# Description for option, no newlines.  Line breaking for e.g. C header
# is automatic.
description: >
  Use a 16-bit object entry and array part sizes (for low memory
  environments).  Also automatically drops support for an object hash
  part to further reduce memory usage; there are rarely large objects
  in low memory environments simply because there's no memory to store
  a lot of properties.

  By default use "description: >" markup which works well for paragraphs
  (replacing newlines with spaces) but includes a trailing newline which
  is also a good default.

# Marker to avoid processing this file.
example: true
