define: DUK_USE_ERRTHROW
feature_enables: DUK_OPT_AUGMENT_ERRORS
introduced: 1.0.0
default: true
tags:
  - ecmascript
description: >
  Call Duktape.errThrow() when augmenting an Ecmascript error object
  about to be thrown.
