define: DUK_USE_HEAPPTR_DEC16
feature_snippet: |
  #if defined(DUK_OPT_HEAPPTR_DEC16)
  #define DUK_USE_HEAPPTR_DEC16(udata,ptr) DUK_OPT_HEAPPTR_DEC16((udata),(ptr))
  #else
  #undef DUK_USE_HEAPPTR_DEC16
  #endif
introduced: 1.1.0
requires:
  - DUK_USE_HEAPPTR16
default: false
tags:
  - lowmemory
  - experimental
description: >
  Use together with DUK_USE_HEAPPTR16 for heap pointer compression.
  DUK_USE_HEAPPTR_DEC16(udata,x) is a macro with a userdata and duk_uint16_t
  argument, and a void ptr return value.  The userdata argument is the heap
  userdata value given at heap creation.
