define: DUK_USE_BUFLEN16
feature_enables: DUK_OPT_BUFLEN16
introduced: 1.1.0
default: false
tags:
  - lowmemory
  - experimental
description: >
  Use a 16-bit buffer length field (for low memory environments).
