define: DUK_USE_ALIGN_BY
feature_snippet: |
  #if !defined(DUK_USE_ALIGN_BY)
  #if defined(DUK_OPT_FORCE_ALIGN)
  #define DUK_USE_ALIGN_BY DUK_OPT_FORCE_ALIGN
  #else
  #define DUK_USE_ALIGN_BY 8
  #endif
  #endif
feature_no_default: true  # provided by architecture unless forced
introduced: 1.3.0
default: 8
tags:
  - portability
description: >
  Use N-byte alignment for 64-bit integers and IEEE doubles
  (supported values are 1, 4, and 8).
