// !!! DONT MODIFY THIS FILE DIRECTLY OR YOU WILL LOST THE CHANGE !!!
// THE FILE WAS GENERATED BY github.com/huxingyi/libphone/tools/phonelayout

#include "libphone.h"
#include "layout.h"

signInPage *signInPageCreate(int parent) {
  signInPage *page = (signInPage *)calloc(1, sizeof(signInPage));
  page->_parent = parent;
  page->backgroundImage = phoneCreateContainerView(0, 0);
  phoneSetViewBackgroundColor(page->backgroundImage, 0xffffff);
  page->logoText = phoneCreateTextView(page->backgroundImage, 0);
  phoneSetViewFontColor(page->logoText, 0x333333);
  phoneSetViewText(page->logoText, "libphone");
  page->usernameTitle = phoneCreateTextView(page->backgroundImage, 0);
  phoneSetViewAlign(page->usernameTitle, PHONE_VIEW_ALIGN_LEFT);
  phoneSetViewFontColor(page->usernameTitle, 0x333333);
  phoneSetViewText(page->usernameTitle, "Username");
  page->usernameInputUnderline = phoneCreateContainerView(page->backgroundImage, 0);
  phoneSetViewBackgroundColor(page->usernameInputUnderline, 0xaaaaaa);
  page->usernameInput = phoneCreateEditTextView(page->backgroundImage, 0);
  phoneSetEditTextViewPlaceholder(page->usernameInput, "helloworld@gmail.com", 0xcccccc);
  phoneSetViewFontColor(page->usernameInput, 0xaaaaaa);
  page->passwordTitle = phoneCreateTextView(page->backgroundImage, 0);
  phoneSetViewAlign(page->passwordTitle, PHONE_VIEW_ALIGN_LEFT);
  phoneSetViewFontColor(page->passwordTitle, 0x333333);
  phoneSetViewText(page->passwordTitle, "123456");
  page->forgotPasswordTitle = phoneCreateTextView(page->backgroundImage, 0);
  phoneSetViewAlign(page->forgotPasswordTitle, PHONE_VIEW_ALIGN_RIGHT);
  phoneSetViewFontColor(page->forgotPasswordTitle, 0x333333);
  phoneSetViewText(page->forgotPasswordTitle, "Forgot");
  page->passwordInputUnderline = phoneCreateContainerView(page->backgroundImage, 0);
  phoneSetViewBackgroundColor(page->passwordInputUnderline, 0xaaaaaa);
  page->passwordInput = phoneCreateEditTextView(page->backgroundImage, 0);
  phoneSetViewInputType(page->passwordInput, PHONE_INPUT_PASSWORD);
  phoneSetViewAlign(page->passwordInput, PHONE_VIEW_ALIGN_LEFT);
  phoneSetViewFontColor(page->passwordInput, 0xaaaaaa);
  phoneSetViewText(page->passwordInput, "123456");
  page->signInButton = phoneCreateContainerView(page->backgroundImage, 0);
  phoneSetViewBackgroundColor(page->signInButton, 0x21c064);
  page->signInButtonText = phoneCreateTextView(page->signInButton, 0);
  phoneSetViewFontColor(page->signInButtonText, 0xffffff);
  phoneSetViewText(page->signInButtonText, "Sign In");
  signInPageLayout(page);
  return page;
}

void signInPageLayout(signInPage *page) {
  float displayWidth = phoneGetViewWidth(page->_parent);
  float displayHeight = phoneGetViewHeight(page->_parent);
  phoneSetViewFrame(page->backgroundImage, 0, 0, displayWidth, displayHeight * 1.08108108108);
  phoneSetViewFontSize(page->logoText, displayHeight * 0.103124155405);
  phoneSetViewFrame(page->logoText, 0, displayHeight * 0.186740709459, displayWidth, displayHeight * 0.103124155405);
  phoneSetViewFontSize(page->usernameTitle, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->usernameTitle, displayWidth * 0.0413793103448, displayHeight * 0.546527449324, displayWidth, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->usernameInputUnderline, displayWidth * 0.0406896551724, displayHeight * 0.639358108108, displayWidth * 0.911724137931, displayHeight * 0.00295608108108);
  phoneSetViewFontSize(page->usernameInput, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->usernameInput, displayWidth * 0.0413793103448, displayHeight * 0.593465371622, displayWidth, displayHeight * 0.0299151182432);
  phoneSetViewFontSize(page->passwordTitle, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->passwordTitle, displayWidth * 0.0413793103448, displayHeight * 0.674483530405, displayWidth, displayHeight * 0.0299151182432);
  phoneSetViewFontSize(page->forgotPasswordTitle, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->forgotPasswordTitle, displayWidth * 0.653793103448, displayHeight * 0.720936233108, displayWidth * 0.297335172414, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->passwordInputUnderline, displayWidth * 0.0406896551724, displayHeight * 0.767314189189, displayWidth * 0.911724137931, displayHeight * 0.00295608108108);
  phoneSetViewFontSize(page->passwordInput, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->passwordInput, displayWidth * 0.0413793103448, displayHeight * 0.720936233108, displayWidth * 0.620689655172, displayHeight * 0.0299151182432);
  phoneSetViewFrame(page->signInButton, displayWidth * 0.0413793103448, displayHeight * 0.849239864865, displayWidth * 0.910016551724, displayHeight * 0.0971879222973);
  phoneSetViewCornerRadius(page->signInButton, displayWidth * 0.0137931034483);
  phoneSetViewFontSize(page->signInButtonText, displayHeight * 0.0348374155405);
  phoneSetViewFrame(page->signInButtonText, 0, displayHeight * 0.0339294763514, displayWidth * 0.910016551724, displayHeight * 0.0348374155405);
}

