// !!! DONT MODIFY THIS FILE DIRECTLY OR YOU WILL LOST THE CHANGE !!!
// THE FILE WAS GENERATED BY github.com/huxingyi/libphone/tools/phonelayout

#ifndef __signInPage_H__
#define __signInPage_H__

typedef struct signInPage {
  int _parent;
  int backgroundImage;
  int logoText;
  int usernameTitle;
  int usernameInputUnderline;
  int usernameInput;
  int passwordTitle;
  int forgotPasswordTitle;
  int passwordInputUnderline;
  int passwordInput;
  int signInButton;
  int signInButtonText;
} signInPage;

signInPage *signInPageCreate(int parent);
void signInPageLayout(signInPage *page);

#endif

