os:
  - osx
  - linux

sudo: required

language: c

before_install:
  # For 32bit tools like adb
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # Android NDK
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xf android-ndk-r9c-linux-x86_64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export ANDROID_NDK_HOME=$PWD/android-ndk-r9c; fi
  # Android SDK
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xzf android-sdk_r23.0.2-linux.tgz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export ANDROID_HOME=$PWD/android-sdk-linux; fi
  # Set PATH
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}; fi
  # Update Android SDK
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t tools --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t platform-tools --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t android-19 --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t sys-img-armeabi-v7a-android-19 --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t build-tools-19.1.0 --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t extra-android-support --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t extra-android-m2repository --force --no-ui; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t extra-google-m2repository --force --no-ui; fi
  # Lets check if adb works
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then adb version; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python .travis/testandroid.py beforeScript; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python .travis/testandroid.py script; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python .travis/testios.py; fi
